name: Remove Member to Mailman

on:
  workflow_dispatch:
    inputs:
      email_address:
        description: 'Email address to remove'
        required: true
        type: string

jobs:
  add-member:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Or your preferred version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Run Selenium script
      env:
        TESTPASSWORD: ${{ secrets.TESTPASSWORD }}
        EMAIL_ADDRESS: ${{ github.event.inputs.email_address }}
      run: python scripts/remove_member.py
