name: Non-Prod mailman automation
on:
  workflow_dispatch:

jobs:
  mailman-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install requirements (jq, Python, Selenium, Chrome)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip jq chromium-browser
          python3 -m pip install --upgrade pip
          pip3 install selenium webdriver-manager

      - name: Fetch ServiceNow tasks, build main array structure
        id: fetch-and-build-main-array
        env:
          SN_USER: ${{ secrets.SERVICECONNECT_USERNAME }}
          SN_PASS: ${{ secrets.SERVICECONNECT_PASSWORD }}
        run: |
          set -e
          DESCS=(
            "Add user to CASS ebrief."
            "Remove user to CASS ebrief."
            "Add user to Academic ebrief"
            "Remove user Academic ebrief"
            "Add user to non-Academic ebrief"
            "Remove user from non-Academic ebrief"
          )
          main_array="["
          for i in {0..5}; do
            DESC="${DESCS[$i]}"
            # 1. Fetch tasks with state=1, active, matching description
            QUERY="active=true^state=1^short_description=$DESC"
            ENCODED_QUERY=$(python3 -c "import urllib.parse; print(urllib.parse.quote('${QUERY}'))")
            URL="https://utsdevesm.service-now.com/api/now/table/sc_task?sysparm_query=${ENCODED_QUERY}&sysparm_fields=number,request_item"
            TASKS_RESP=$(curl -s -u "$SN_USER:$SN_PASS" -H "Accept: application/json" "$URL")
            TASK_JSON=$(echo "$TASKS_RESP" | jq '.result')
            TASK_COUNT=$(echo "$TASK_JSON" | jq 'length')
            tasks_array="[]"
            emails_array="[]"
            if [[ "$TASK_COUNT" -gt 0 ]]; then
              tasks_array=$(echo "$TASK_JSON" | jq -r '[.[].number]')
              declare -a email_list=()
              for idx in $(seq 0 $((TASK_COUNT-1))); do
                ritm_sysid=$(echo "$TASK_JSON" | jq -r ".[$idx].request_item.value // empty")
                if [[ -z "$ritm_sysid" || "$ritm_sysid" == "null" ]]; then
                  email_list+=("\"error-No request_item\"")
                  continue
                fi
                # Get requested_for sys_id
                REQ_FOR_SYSID=$(curl -s -u "$SN_USER:$SN_PASS" \
                  -H "Accept: application/json" \
                  "https://utsdevesm.service-now.com/api/now/table/sc_req_item?sysparm_query=sys_id=${ritm_sysid}&sysparm_fields=requested_for" \
                  | jq -r '.result[0].requested_for.value // empty')
                if [[ -z "$REQ_FOR_SYSID" || "$REQ_FOR_SYSID" == "null" ]]; then
                  email_list+=("\"error-No requested_for\"")
                  continue
                fi
                # Get email
                EMAIL=$(curl -s -u "$SN_USER:$SN_PASS" \
                  -H "Accept: application/json" \
                  "https://utsdevesm.service-now.com/api/now/table/sys_user?sysparm_query=sys_id=${REQ_FOR_SYSID}&sysparm_fields=email" \
                  | jq -r '.result[0].email // empty')
                if [[ -z "$EMAIL" || "$EMAIL" == "null" ]]; then
                  email_list+=("\"error-Email not found\"")
                else
                  email_list+=("\"$EMAIL\"")
                fi
              done
              emails_array="[$(IFS=,; echo "${email_list[*]}")]"
            fi
            group_part="[${tasks_array},${emails_array},[]]"
            main_array+="$group_part"
            if [ $i -lt 5 ]; then main_array+=","; fi
          done
          main_array+="]"
          echo "$main_array" > mailman_main_array.json
          echo "Final main_array structure:"
          cat mailman_main_array.json

      - name: Add/remove members for all lists and fill in responses
        env:
          CASS_ADD_PW: ${{ secrets.CASS_PASSWORD }}
          CASS_REMOVE_PW: ${{ secrets.CASS_PASSWORD }}
          ACAD_ADD_PW: ${{ secrets.ACAD_PASSWORD }}
          ACAD_REMOVE_PW: ${{ secrets.ACAD_PASSWORD }}
          NACAD_ADD_PW: ${{ secrets.NACAD_PASSWORD }}
          NACAD_REMOVE_PW: ${{ secrets.NACAD_PASSWORD }}
        run: |
          set -e
          urls=(
            "https://<CASS_MAILMAN_URL>/add"
            "https://<CASS_MAILMAN_URL>/remove"
            "https://<ACAD_MAILMAN_URL>/add"
            "https://<ACAD_MAILMAN_URL>/remove"
            "https://<NACAD_MAILMAN_URL>/add"
            "https://<NACAD_MAILMAN_URL>/remove"
          )
          pws=(
            "$CASS_ADD_PW"
            "$CASS_REMOVE_PW"
            "$ACAD_ADD_PW"
            "$ACAD_REMOVE_PW"
            "$NACAD_ADD_PW"
            "$NACAD_REMOVE_PW"
          )
          updated_main_array="["
          for idx in {0..5}; do
            arr=$(jq ".[$idx]" mailman_main_array.json)
            tasks=($(echo "$arr" | jq -r '.[0][]'))
            emails=($(echo "$arr" | jq -r '.[1][]'))
            responses=()
            for j in "${!emails[@]}"; do
              email="${emails[$j]}"
              if [[ "$email" == error* ]]; then
                resp="error-email-lookup"
              else
                if [[ $idx =~ ^(0|2|4)$ ]]; then
                  resp=$(python3 scripts/add_member_from_listserv.py "$email" "${urls[$idx]}" "${pws[$idx]}")
                else
                  resp=$(python3 scripts/remove_member_from_listserv.py "$email" "${urls[$idx]}" "${pws[$idx]}")
                fi
              fi
              resp=$(echo "$resp" | sed ':a;N;$!ba;s/\n/\\n/g')
              responses+=("\"$resp\"")
            done
            joined_responses=$(printf "%s," "${responses[@]}")
            joined_responses="[${joined_responses%,}]"
            tasks_json=$(echo "$arr" | jq '.[0]')
            emails_json=$(echo "$arr" | jq '.[1]')
            group="[${tasks_json},${emails_json},${joined_responses}]"
            if [ $idx -eq 0 ]; then
              updated_main_array+="$group"
            else
              updated_main_array+=",$group"
            fi
          done
          updated_main_array+="]"
          echo "$updated_main_array" > mailman_main_array_with_results.json
          cat mailman_main_array_with_results.json

      - name: Update ServiceNow tasks with results
        env:
          SN_USER: ${{ secrets.SERVICECONNECT_USERNAME }}
          SN_PASS: ${{ secrets.SERVICECONNECT_PASSWORD }}
        run: |
          update_task() {
            local TASK="$1"; local NOTE="$2"; local RESULT="$3"
            curl -s -u "$SN_USER:$SN_PASS" \
              --request PATCH \
              --header "Content-Type: application/json" \
              --data "{\"work_notes\": \"$NOTE\"}" \
              "https://utsdevesm.service-now.com/api/now/table/sc_task?sysparm_query=number=${TASK}" > /dev/null
            if [[ ! "$RESULT" =~ ^error ]]; then
              curl -s -u "$SN_USER:$SN_PASS" \
                --request PATCH \
                --header "Content-Type: application/json" \
                --data '{"state":"3","cmdb_ci":{"display_value":"Listserv"}}' \
                "https://utsdevesm.service-now.com/api/now/table/sc_task?sysparm_query=number=${TASK}" > /dev/null
              echo "Closed and set Listserv CI for $TASK"
            else
              echo "Left $TASK open due to error: $RESULT"
            fi
          }
          for g in {0..5}; do
            arr=$(jq ".[$g]" mailman_main_array_with_results.json)
            tasks=($(echo "$arr" | jq -r '.[0][]'))
            emails=($(echo "$arr" | jq -r '.[1][]'))
            results=($(echo "$arr" | jq -r '.[2][]'))
            count=${#tasks[@]}
            for idx in $(seq 0 $((count-1))); do
              t="${tasks[$idx]}"
              e="${emails[$idx]}"
              r="${results[$idx]}"
              update_task "$t" "Mailman: $e : $r" "$r"
            done
          done
