name: Fetch All Mailman Listserv Tasks

on:
  workflow_dispatch:

jobs:
  fetch-all-tasks:
    name: Fetch All Mailman Task Lists
    runs-on: ubuntu-latest
    steps:
      - name: Install jq and python3
        run: sudo apt-get update && sudo apt-get install -y jq python3

      - name: Fetch all 6 task lists and print as array
        id: fetch_tasks
        env:
          SN_USERNAME: ${{ secrets.SERVICECONNECT_USERNAME }}
          SN_PASSWORD: ${{ secrets.SERVICECONNECT_PASSWORD }}
        run: |
          declare -a DESCS=(
            "Add user to CASS ebrief."
            "Remove user to CASS ebrief."
            "Add user to Academic ebrief"
            "Remove user Academic ebrief"
            "Add user to non-Academic ebrief"
            "Remove user from non-Academic ebrief"
          )
          declare -a ALL_TASKS
          for DESC in "${DESCS[@]}"; do
            QUERY="active=true^state=1^short_description=$DESC"
            ENCODED_QUERY=$(python3 -c "import urllib.parse; print(urllib.parse.quote('${QUERY}'))")
            URL="https://utsdevesm.service-now.com/api/now/table/sc_task?sysparm_query=${ENCODED_QUERY}&sysparm_fields=number,short_description"
            RESPONSE=$(curl -s -u "$SN_USERNAME:$SN_PASSWORD" -H "Accept: application/json" "$URL")
            # Print to log
            echo "=== $DESC ==="
            echo "$RESPONSE" | jq -r '.result[] | "\(.number) - \(.short_description)"'
            # Add to array in JSON
            NUMBERS=$(echo "$RESPONSE" | jq -c '[.result[].number]')
            ALL_TASKS+=("$NUMBERS")
          done
          
          # Combine as a JSON array of arrays
          echo ""
          echo "Combined array of arrays:"
          echo "["
          for i in "${!ALL_TASKS[@]}"; do
            if [ "$i" -ne 0 ]; then echo ","; fi
            echo "${ALL_TASKS[$i]}"
          done
          echo "]"
